### ISSUE TITLE
version number 20.010 is inaccurate

### ISSUE THREAD

**Issue by rkingsbury** [conda-forge/packmol-feedstock#10]
It's great to have packmol available via conda-forge. I just wanted to note that the version number of the current build is inaccurate. conda reports v20.010 but the real version is 20.3.1 (which you see when you run the binary).

Hopefully this can be solved in the next release. Thanks!

**Comment by mattwthompson** [comment]
I get an older `20.010` build pulled down instead of more recent `20.3.x` builds, probably because it gets parsed differently:

```
>>> from packaging.version import Version
>>> Version("20.010")
<Version('20.10')>
```

Still, I don't get a mismatch with that build:

```
$ conda list | grep packmol
packmol                   20.010               h508aa58_0    conda-forge
$ packmol

################################################################################

 PACKMOL - Packing optimization for the automated generation of
 starting configurations for molecular dynamics simulations.

                                                              Version 20.010

################################################################################

  Packmol must be run with: packmol < inputfile.inp

  Userguide at: http://m3g.iqm.unicamp.br/packmol

  Reading input file... (Control-C aborts)
^C

**Comment by lmiq** [comment]
This version inconsistency was fixed upstream on Packmol.

**Comment by mikemhenry** [comment]
Once we can confirm the next version we release on conda-forge is correct we can close this issue

**Comment by mikemhenry** [comment]
fixed!
