### ISSUE TITLE
Packmol outdated

### ISSUE THREAD

**Issue by lmiq** [conda-forge/packmol-feedstock#15]
### Comment:

The version of Packmol distributed through Conda seems to be outdated:

https://github.com/m3g/packmol/issues/49

**Comment by mattwthompson** [comment]
The bot has built at least one new package for a more recent version: #14

It just needs a maintainer to look at it and either merge or change it

**Comment by mikemhenry** [comment]
I've scheduled the bot to re-run to try and fix some of the merge conflicts that came in

**Comment by mikemhenry** [comment]
So newer versions should be coming soon!

**Comment by mattwthompson** [comment]
The most recent version is v20.14.4; hopefully we can get that one online soon and worry about older versions as needed

https://github.com/m3g/packmol/releases/tag/v20.14.4%2Bdocs1

**Comment by mikemhenry** [comment]
> The most recent version is v20.14.4; hopefully we can get that one online soon and worry about older versions as needed
> 
> https://github.com/m3g/packmol/releases/tag/v20.14.4%2Bdocs1

Good point! I can make a 20.14.4 release and if people need older ones we can do it as requested (pull requests welcome :smirk: )

**Comment by lmiq** [comment]
There's no reason for using old versions. Packmol has not have breaking versions for years now. (Since a while the versions follow semver as well).

**Comment by mikemhenry** [comment]
> There's no reason for using old versions

Good to know! 

Fixed with https://github.com/conda-forge/packmol-feedstock/pull/21
