### ISSUE TITLE
New maintainers?

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/packmol-feedstock#18]
### Comment:

Hi,

Things have been pretty quiet around here for a while. There are a couple of releases that haven't been shipped yet and would nice to get over the finish line. I'm willing to help out here if another maintainer is willing to either look at some PRs or add me directly (to make it easy: https://github.com/conda-forge/packmol-feedstock/pull/17).

**Comment by mikemhenry** [comment]
Yah It looks like for whatever reason I wasn't getting added to the new version PRs that came in so I missed them, lets get all the releases we can onto conda-forge!
