### ISSUE TITLE
Improve testing

### ISSUE THREAD

**Issue by mikemhenry** [conda-forge/packmol-feedstock#25]
It would be nice to add more testing to validate the build.

**Comment by mikemhenry** [comment]
Looks like upstream has some tests:

https://github.com/m3g/packmol/blob/master/.github/workflows/actions.yml#L40-L44

and the script:

https://github.com/m3g/packmol/blob/master/testing/test.sh

Looks like it needs julia to run, I can make a PR that runs these tests since it looks like it takes only a few minutes max

**Comment by mattwthompson** [comment]
My intent isn't/wasn't to advocate for running all of their unit tests in packaging, but their action appears to be super quick (~30 seconds to setup and build, ~1 minute to run all tests)

https://github.com/m3g/packmol/actions/runs/10392355508/job/28777344417

I'd be just as happy if there are a small number of tests run; IME the 80/20 rule or Pareto Principle applies strongly here
